arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask$ virtualenv --version
15.0.1
arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask$ mkdir .flaskenv && cd .flaskenv
arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask$ cd .flaskenv
arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ virtualenv flask-env
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/arunsk7891/Desktop/Skills/Flask/.flaskenv/flask-env/bin/python2
Not overwriting existing python script /home/arunsk7891/Desktop/Skills/Flask/.flaskenv/flask-env/bin/python (you must use /home/arunsk7891/Desktop/Skills/Flask/.flaskenv/flask-env/bin/python2)
Installing setuptools, pkg_resources, pip, wheel...done.
arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ source flask-env/bin/activate
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ pip install Flask
Requirement already satisfied: Flask in ./flask-env/lib/python2.7/site-packages (0.12.2)
Requirement already satisfied: Jinja2>=2.4 in ./flask-env/lib/python2.7/site-packages (from Flask) (2.10)
Requirement already satisfied: Werkzeug>=0.7 in ./flask-env/lib/python2.7/site-packages (from Flask) (0.14.1)
Requirement already satisfied: click>=2.0 in ./flask-env/lib/python2.7/site-packages (from Flask) (6.7)
Requirement already satisfied: itsdangerous>=0.21 in ./flask-env/lib/python2.7/site-packages (from Flask) (0.24)
Requirement already satisfied: MarkupSafe>=0.23 in ./flask-env/lib/python2.7/site-packages (from Jinja2>=2.4->Flask) (1.0)
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ python helloworld.py
python: can't open file 'helloworld.py': [Errno 2] No such file or directory
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ f= open("guru99.txt","w+")
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ f= open("guru99.txt","w+");
bash: syntax error near unexpected token `('
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ f= open "helloworld.py","w+"
Couldn't get a file descriptor referring to the console
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ f= open ("helloworld.py","w+")
bash: syntax error near unexpected token `('
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ ^C
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ vi helloworld.py

[1]+  Stopped                 vi helloworld.py
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ vi helloworld.py

[2]+  Stopped                 vi helloworld.py
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ vi helloworld.py
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ from flask import Flask
from: can't read /var/mail/flask
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ 
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ app = Flask(__name__)
bash: syntax error near unexpected token `('
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ 
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ @app.route("/") 
bash: syntax error near unexpected token `"/"'
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ def hello(): 
bash: syntax error near unexpected token `('
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$     return "Hello World!"
bash: return: Hello World!: numeric argument required
bash: return: can only `return' from a function or sourced script
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ 
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ 
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ if (__name__ == "__main__"): 
bash: syntax error near unexpected token `:'
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ python helloworld.py
 * Running on http://127.0.0.1:5001/ (Press CTRL+C to quit)
127.0.0.1 - - [08/Apr/2018 20:47:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Apr/2018 20:47:07] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2018 20:48:23] "GET / HTTP/1.1" 200 -
^C----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 42768)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/home/arunsk7891/Desktop/Skills/Flask/.flaskenv/flask-env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/arunsk7891/Desktop/Skills/Flask/.flaskenv/flask-env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 324, in handle_one_request
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.7/socket.py", line 451, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
----------------------------------------
^C----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 42772)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/home/arunsk7891/Desktop/Skills/Flask/.flaskenv/flask-env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/arunsk7891/Desktop/Skills/Flask/.flaskenv/flask-env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 324, in handle_one_request
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.7/socket.py", line 451, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
----------------------------------------
^C----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 42776)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/home/arunsk7891/Desktop/Skills/Flask/.flaskenv/flask-env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/arunsk7891/Desktop/Skills/Flask/.flaskenv/flask-env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 324, in handle_one_request
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.7/socket.py", line 451, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
----------------------------------------
127.0.0.1 - - [08/Apr/2018 20:50:43] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 42778)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
127.0.0.1 - - [08/Apr/2018 20:50:44] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 42780)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
127.0.0.1 - - [08/Apr/2018 20:50:44] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Apr/2018 20:50:44] "GET /favicon.ico HTTP/1.1" 404 -
^C(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ python helloworld.py
 * Running on http://127.0.0.1:5001/ (Press CTRL+C to quit)
127.0.0.1 - - [08/Apr/2018 20:50:59] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Apr/2018 20:51:06] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Apr/2018 20:51:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Apr/2018 20:51:32] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Apr/2018 20:51:40] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Apr/2018 20:52:13] "GET / HTTP/1.1" 200 -
^C----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 42820)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/home/arunsk7891/Desktop/Skills/Flask/.flaskenv/flask-env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/arunsk7891/Desktop/Skills/Flask/.flaskenv/flask-env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 324, in handle_one_request
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.7/socket.py", line 451, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
----------------------------------------
^C----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 42824)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/home/arunsk7891/Desktop/Skills/Flask/.flaskenv/flask-env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/arunsk7891/Desktop/Skills/Flask/.flaskenv/flask-env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 324, in handle_one_request
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.7/socket.py", line 451, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
----------------------------------------
^C(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv$ mkdir static && cd static
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static$ touch app.js
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static$ alert("you are feeling app.js!");
bash: syntax error near unexpected token `('
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static$ mkdir static && cd static
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static/static$ touch app.js
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static/static$ touch app.js
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static/static$ ls
app.js
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static/static$ vi app.js
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static/stati(flask-env)(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static/static$ 
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static/static$ 
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static/static$ 
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static/static$ ls
app.js
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static/static$ cd .flaskenv
bash: cd: .flaskenv: No such file or directory
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static/static$ vi helloworld.py
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static/static$ python helloworld.py
 * Running on http://127.0.0.1:5001/ (Press CTRL+C to quit)
127.0.0.1 - - [08/Apr/2018 21:03:16] "GET /static/app.js HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2018 21:03:22] "GET /static/app.js HTTP/1.1" 404 -
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static/static$ vi helloworld.py
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static/static$ python helloworld.py
 * Running on http://127.0.0.1:5001/ (Press CTRL+C to quit)
127.0.0.1 - - [08/Apr/2018 21:03:50] "GET /static/app.js HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2018 21:03:51] "GET /static/app.js HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2018 21:03:51] "GET /static/app.js HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2018 21:03:52] "GET /static/app.js HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2018 21:03:52] "GET /static/app.js HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2018 21:03:52] "GET /static/app.js HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2018 21:03:52] "GET /static/app.js HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2018 21:03:56] "GET /static/app.js HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2018 21:03:56] "GET /static/app.js HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2018 21:03:56] "GET /static/app.js HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2018 21:03:56] "GET /static/app.js HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2018 21:03:56] "GET /static/app.js HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2018 21:03:57] "GET /static/app.js HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2018 21:03:57] "GET /static/app.js HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2018 21:03:57] "GET /static/app.js HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2018 21:03:57] "GET /static/app.js HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2018 21:03:57] "GET /static/app.js HTTP/1.1" 404 -
^C----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 43034)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/home/arunsk7891/Desktop/Skills/Flask/.flaskenv/flask-env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 293, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/arunsk7891/Desktop/Skills/Flask/.flaskenv/flask-env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 324, in handle_one_request
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.7/socket.py", line 451, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
----------------------------------------

\\



^C(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static/static$ 
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static/static$ 
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static/static$ 
(flask-env) arunsk7891@arun-HP-Ubuntu:~/Desktop/Skills/Flask/.flaskenv/static/static$ 

